### ISSUE TITLE
Internal server error, something went wrong during 

### ISSUE THREAD

**Issue by eduadiez** [prysmaticlabs/prysm-web-ui#100]
During the `Processing deposits from Ethereum 1 chain` process the message `Internal server error, something went wrong` appears constantly repeated, once it's processed the error disappears.

<img width="1352" alt="Screenshot 2020-11-26 at 21 01 37" src="https://user-images.githubusercontent.com/20141918/100388469-fad5b000-302a-11eb-8ea7-183d873e5e68.png">

**Comment by Poweriser-1** [comment]
That is, the picture will not change until December 12?

**Comment by rauljordan** [comment]
Errors are now more informative, saying that chain has not started
