### ISSUE TITLE
Requesting version info in the UI

### ISSUE THREAD

**Issue by ruvenni** [prysmaticlabs/prysm-web-ui#107]
We think it would be pretty convenient if the UI could show clearly somewhere what Beacon-Chain and Prysm client version is currently running.

**Comment by mohamedmansour** [comment]
@rauljordan 

I am working on this.

Some follow up questions:
- How important is it to show the version on every screen?
- Should we hide it in the footer? In the header? 
- Should we have a dedicated page that showcases the version? We can add other things to it like Github Issues/Documentation etc. We can add an indicator in the new "About" page whether each version is updated or requires to be updated. We can add license information etc.

**Comment by mohamedmansour** [comment]
Some research on how versions are in products:

Discord:
![image](https://user-images.githubusercontent.com/68524/102699117-40833400-41f7-11eb-8152-754630ad9702.png)

Microsoft Edge Browser:
![image](https://user-images.githubusercontent.com/68524/102699126-555fc780-41f7-11eb-85f6-5005701c1660.png)

Grafana on the footer:
![image](https://user-images.githubusercontent.com/68524/102699158-8c35dd80-41f7-11eb-8d03-03d287ce2186.png)

**Comment by mohamedmansour** [comment]
@rauljordan For the initial draft, I just added it to the sidebar, I am a fan if we create another navigation named "About" and we can place the "Read the Docs" as a link there, including license information, Github URL, and the Version information. We can have "version checks" in future too.

So End to End looks like:
![image](https://user-images.githubusercontent.com/68524/102701281-4df5e980-420a-11eb-9940-1d5aad89480b.png)

**Comment by mohamedmansour** [comment]
@rauljordan have we decided a design on where to place the version information? Do we want to hide it behind an "about" page?

**Comment by mohamedmansour** [comment]
@rauljordan do you know how I can build a versioned binary of beacon/validator so I can see v1.0.6 and not the git hash?
