### ISSUE TITLE
Failed to load resource: net::ERR_CONNECTION_REFUSED at 127.0.0.1:3500/eth/v1alpha1/beacon/chainhead

### ISSUE THREAD

**Issue by MikeJerred** [prysmaticlabs/prysm-web-ui#111]
I am running the prysm validator with --grpc-gateway 192.168.1.138 (the local IP of my server node), and when opening the webUI on my other machine (by visiting 192.168.1.138:7500) the web ui loads but then has lots of errors saying:

```
Failed to load resource: net::ERR_CONNECTION_REFUSED at 127.0.0.1:3500/eth/v1alpha1/beacon/chainhead
```

The web ui is maybe hardcoded to request some data from 127.0.0.1 instead of using the configured grpc-gateway, or perhaps I have set it up incorrectly?

**Comment by kaiji191** [comment]
same issue

**Comment by MikeJerred** [comment]
Note: I have managed to workaround this by follow Step 4 here: https://docs.prylabs.network/docs/prysm-usage/web-interface#step-4-accessing-the-web-interface-from-a-remote-computer
i.e. using ssh -L 7500:127.0.0.1:7500 user@192.168.1.138 but it would be preferable to connect directly instead of using this ssh tunneling

**Comment by rauljordan** [comment]
This will be resolved by https://github.com/prysmaticlabs/prysm/issues/7984, please track the progress in that issue for a resolution
