### ISSUE TITLE
Importing new validators blanks out current validator balance (web-ui)

### ISSUE THREAD

**Issue by BiggT76** [prysmaticlabs/prysm-web-ui#114]
# 🐞 Bug Report

### Description

 When importing new validators into a current wallet, current balance is either "0" or "n/a" in web portal until beacon chain deposit confirmation

### Has this worked before in a previous version?

 Not sure, first attempt.

## 🔬 Minimal Reproduction

Run validator 1 and wait for deposit confirmation (my validator was actively processing at the time).  Import a new validator _before_ the beacon chain can confirm the deposit.

## 🔥 Error
![image](https://user-images.githubusercontent.com/6043075/100946197-d5d0b980-34d0-11eb-9714-c7f8e4fb72da.png)

And the scarier one:
![image](https://user-images.githubusercontent.com/6043075/100946768-0f55f480-34d2-11eb-92bc-4c3086ae2a36.png)

Grafana did the same thing but after about a minute, it showed a balance on validator 1. Everything showed correctly on https://beaconcha.in.
![image](https://user-images.githubusercontent.com/6043075/100946364-29430780-34d1-11eb-9892-88925df8d276.png)

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
Firefox 83.0
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
Prysm v1.0.3
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by mohamedmansour** [comment]
I am trying to reproduce this, I let me deposit go through and waited, then I imported the private key in the keystore.
![image](https://user-images.githubusercontent.com/68524/101967972-c38e0400-3bd1-11eb-9dc1-577038c1537e.png)
![image](https://user-images.githubusercontent.com/68524/101967976-c8eb4e80-3bd1-11eb-9242-a6027cdca14c.png)

**Comment by mohamedmansour** [comment]
Interesting, I created a new key, without depositing a transaction, and uploaded it. The total balance decreased to just one:
![image](https://user-images.githubusercontent.com/68524/101968227-e79e1500-3bd2-11eb-86a1-512f947dfb25.png)
![image](https://user-images.githubusercontent.com/68524/101968234-ef5db980-3bd2-11eb-9cc2-12d5951dd304.png)

**Comment by rauljordan** [comment]
Working on this today
