### ISSUE TITLE
How to restore access to Non-HD wallets (Importing Keystores)

### ISSUE THREAD

**Issue by VTsuprov** [prysmaticlabs/prysm-web-ui#115]
I have created Non-HD wallet (Importing Keystores) for beacon chain and I have lost Web password and Wallet password.
I'm running Prysm on Dappnode.
Am I right that I can delete the existing walet and recreate a new one from my validator_keys files. I guess, in case of Dapnode the easest way is to delete the Prysm and reinstall it again?

**Comment by rauljordan** [comment]
> Am I right that I can delete the existing walet and recreate a new one from my validator_keys files
This is indeed the best approach @VTsuprov. I would first stop your validator, backup the `validator.db` file contained within your walletdirectory/direct folder to some external machine, then, I would delete the wallet and import it again from scratch
