### ISSUE TITLE
Downloadable earnings report

### ISSUE THREAD

**Issue by jwhelan72** [prysmaticlabs/prysm-web-ui#139]
It would be helpful to have the ability to download (via CSV) a daily earnings report within a given date range for the set of validators being run by an operator.  This feature would be extremely useful both for general record keeping and for tax reporting.

**Comment by JHGrove3** [comment]
I'll do an add on to that idea -- Allow it to automatically create a report on a schedule. 

For example, tell it to pull a report at Midnight on the first of every month, so you get a snapshot of the previous month's final performance.

The export could be saved to a file which could be downloaded later by clicking a link, or it could be emailed to someone.

**Comment by nomonkeynodeal** [comment]
Not only would this be extremely convenient, it is a no-brainer mandatory feature given we have to track earnings.

**Comment by prestonvanloon** [comment]
This likely requires a large backend change in Prysm to support historical data queries.

**Comment by rkapka** [comment]
Related: https://github.com/prysmaticlabs/prysm/issues/8372
