### ISSUE TITLE
Have the "Items per Page" drop downs remember the last selection

### ISSUE THREAD

**Issue by JHGrove3** [prysmaticlabs/prysm-web-ui#155]
Is your feature request related to a problem? Please describe.

There are two drop downs labeled "Items per Page" in the Prysm app
One is on the Validator Gains and Losses page:
http://prysm.dappnode/dashboard/gains-and-losses

The other is on the Validator Accounts List page:
http://prysm.dappnode/dashboard/wallet/accounts

When coming to these pages, both dropdowns always default to 5. If you have 6 or more validators, you always have to change the dropdown to a higher number in order to see them all.

Describe the solution you'd like

I would like the drop down to remember what you chose the last time you visited the page, and default to that number when you return to the page.

I would also like both dropdowns to have the same number of entries. Currently the Accounts page can show up to 250 entries, while the Gains and Losses page has a maximum of 100 entries that it can display.  For simplicity, both should be able to show up to 250 entries.

Describe alternatives you've considered

You could also have a setting in the app, where you indicate what you want to default value to be when you visit the page.

Additional context

This is also an issue on the Prysm Pyrmont app.

Note that separately I just entered a bug report that when you change the "Items per Page" dropdown on the Accounts List page, it breaks the sorting feature on that page.

**Comment by rauljordan** [comment]
Done by @olehyev138

**Comment by JHGrove3** [comment]
Update: The UI now remembers the user's selection of how many items to display, but it doesn't use that information on the first page load.

So the dropdown might say "10" but it still only shows 5 entries when you first load the page.

The page needs to check that stored value on initial page load, before it generates the list of entries for the first time.
