### ISSUE TITLE
Change the location and/or load timing of the "Import Keystores" button

### ISSUE THREAD

**Issue by JHGrove3** [prysmaticlabs/prysm-web-ui#156]
Is your feature request related to a problem? Please describe.

If you want to add a new keystore(s) to the app, you must go to the Account List page to do it.
http://prysm.dappnode/dashboard/wallet/accounts

There is a large orange button in the upper-right of that page that you can click to start the process.

That button does not appear until after the page has loaded the list of current keystores.

I had an issue where I was able to install prysm (prysm pyrmont at the time) without having a keystore yet (I think I gave a fake keystore password or somethimg). This was good because it allowed Prysm to start syncing the beacon chain while I was creating my keys etc.

But when I wanted to upload my first keystore I came to the Accounts List page and it just kept endlessly loading, trying to show a list of keystores that it didn't have.

The problem was that the orange "Import Keystores" button would not appear until AFTER it finished loading the validator table, and it was not able to get to that point.

If the button had appeared first, it would not have been a problem.

If the Import Keystores button also existed on the home page, it would not be a problem.

But as it was, I had to delete the app and reinstall, because I couldn't add a keystore.

Recently another person had the same thing happen; I think their initial wallet load didn't complete correctly, and they were trying to finish the job.

Describe the solution you'd like

Either display the Import Keystores button before loading the table of keystores, or add the button to another page, like the home page.

Describe alternatives you've considered

You might also change the install procedure to allow people to install and start Prysm without a keystore. It would simplify the installation process, make it easier for users to figure out which passwords aren't working (UI password, wallet password, keystore password). It would also allow the Beacon Chain sync process to start immediately, and not wait until after they have created their first key

Additional context

**Comment by rauljordan** [comment]
Done by @olehyev138
