### ISSUE TITLE
Incorrect keystore error message is badly formatted

### ISSUE THREAD

**Issue by rkapka** [prysmaticlabs/prysm-web-ui#166]
1. Go to Import Keystores page
2. Import a non-keystore JSON file
3. Take a look at the error message

![obraz](https://user-images.githubusercontent.com/28876818/110760994-8a584500-824f-11eb-9832-fbba6d8fbaea.png)

**Comment by mohamedmansour** [comment]
I cannot repro this. Always looks like the following:
![image](https://user-images.githubusercontent.com/68524/116727727-c8ddc680-a999-11eb-9d68-7b475c02de2f.png)

**Comment by rkapka** [comment]
You are right, this is no longer an issue.
