### ISSUE TITLE
How can i reset my password

### ISSUE THREAD

**Issue by Jason-Wanxt** [prysmaticlabs/prysm-web-ui#177]
I just forgot my password of web interface, is there any process i can do to reset it?

**Comment by rauljordan** [comment]
Delete a file called rpc-password-hash that you should find inside your wallet directory

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Jason-Wanxt ***@***.***>
Sent: Sunday, April 25, 2021 2:03:42 AM
To: prysmaticlabs/prysm-web-ui ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [prysmaticlabs/prysm-web-ui] How can i reset my password (#177)


I just forgot my password o web interface, is there any process i can do to reset it?

**Comment by Jason-Wanxt** [comment]
Thx, i have reset it by fellowing this way.
