### ISSUE TITLE
Add HTTP Secure Headers

### ISSUE THREAD

**Issue by dnkolegov** [prysmaticlabs/prysm-web-ui#178]
The HTTP responses from WebUI do not contain secure headers.

At least, WebUI MUST provide an X-Frame-Options header to be protected against Clickjacking attack.
At the present,  WebUI can be framed and employed by malicious actors to trick users.

Other useful headers are described here:
https://web.dev/security-headers/

The minimal recommended set: HSTS, X-Frame-Options, and X-Content-Type-Options

**Comment by james-prysm** [comment]
Fixed with next release of prysm.
