### ISSUE TITLE
"public_keys": illegal base64 data at input byte 8

### ISSUE THREAD

**Issue by ardevd** [prysmaticlabs/prysm-web-ui#181]
After updating to v1.3.10 I'm getting the following error when accessing the Prysm web dashboard: `parsing list "public_keys": illegal base64 data at input byte 8`

Attestation was successful though so it seems like the validator is running fine after the update
but the web dashboard doesn't load

**Comment by prestonvanloon** [comment]
Broken by https://github.com/prysmaticlabs/ethereumapis/pull/245

**Comment by rkapka** [comment]
> Broken by [prysmaticlabs/ethereumapis#245](https://github.com/prysmaticlabs/ethereumapis/pull/245)

This change touched the new `v1` protos, but the Web UI relies on our old `v1alpha1` protos.

**Comment by prestonvanloon** [comment]
This will be fixed in the next release. The fix has merged to develop in Prysm https://github.com/prysmaticlabs/prysm/pull/8988

**Comment by rkapka** [comment]
This has been fixed in 1.3.10
