### ISSUE TITLE
Web Dashboard can't read existing wallet

### ISSUE THREAD

**Issue by famunger** [prysmaticlabs/prysm-web-ui#183]
# 🐞 Bug Report

### 
On my Avado I open the Prysm web dashboard but I doesn't read the existing wallet. Instead it start with the onboarding page. The validators are running and do attestations (accordings to logs) though.

 A clear and concise description of the problem...

### Has this worked before in a previous version?
Yes!

 Yes, the previous version in which this bug was not present was: ....

## 🔬 Minimal Reproduction

Reproducable on any avado - several users have same issue.

## 🔥 Error

<pre><code>

</code></pre>

Error code. "parsing list "public_keys":illegal base64 data at input byte 8"

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

AVADO

**What version of Prysm are you running? (Which release)**

<pre>
  <code>

  </code>
</pre>

Version: 0.0.26 QmTcpBE6kTkWwE68ZJV8VL97NNfKH7mcXS7e56vVk7Gpyy

**Anything else relevant (validator index / public key)?**

**Comment by nomonkeynodeal** [comment]
This is what I just experienced.

**Comment by rkapka** [comment]
> Error code. "parsing list "public_keys":illegal base64 data at input byte 8"

This was fixed in 1.3.11
