### ISSUE TITLE
Recent Epoch Gains/Loses Dashboard Error

### ISSUE THREAD

**Issue by danielrees-eth** [prysmaticlabs/prysm-web-ui#210]
The "Best Performing Validator" and "Worst Performing Validator" bars on the dashboard are mixed up. The bar labeled "Best Performing Validator" is in fact the worst performing validator, and vice versa.

![Screenshot from 2021-11-17 12-57-22](https://user-images.githubusercontent.com/12661581/142265046-2bb81203-911b-43c5-8dfe-809a0d3ccf76.png)

**Comment by james-prysm** [comment]
we are removing this graph in the next release, please continue to use grafana and other monitoring tools like beaconcha.in to monitor your performance. we will be evaluating potential monitoring improvements to the prysm UI in the future. Thanks for sending back some feedback.
