### ISSUE TITLE
Type error "syncing to latest head not ready to response"

### ISSUE THREAD

**Issue by pablomendezroyo** [prysmaticlabs/prysm-web-ui#213]
When installing Prysm and using it together with the Prysm-UI, the UI must wait until the beaconchain is synced to work properly. The error given is
![image](https://user-images.githubusercontent.com/41727368/143222060-7642d4b2-6b16-48cd-a0d9-6f13d4d6d20b.png)

Would be great to type this error and show a more friendly UI component so users do not get into panic and know better what's going on

**Comment by james-prysm** [comment]
we will look into providing an api and overlay to describe the current state of syncing at a future date. for now we will address this by not throwing a popup while the beacon node is syncing as a temporary fix
