### ISSUE TITLE
Allow to change the JWT from the UI

### ISSUE THREAD

**Issue by pablomendezroyo** [prysmaticlabs/prysm-web-ui#214]
In the latest release, there was introduced a JWT (JSON web token) that is generated in the CLI and must be used in the first login.

Would be great that users are allowed to change this JWT directly from the UI, so all the process is automatic and the UI already knows what is the `auth-token` path and change it with `validator web generate-auth-token...`

**Comment by james-prysm** [comment]
unfortunately, this would compromise the security of the token command and therefore can't support it.
