### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by Mettodo** [prysmaticlabs/prysm-web-ui#225]
Hello I got this error message when entering Prysm for the first time: 
{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 500,
  "statusText": "Internal Server Error",
  "url": "http://gnosis-beacon-chain-prysm.dappnode/api/v2/validator/beacon/queue",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for http://gnosis-beacon-chain-prysm.dappnode/api/v2/validator/beacon/queue: 500 Internal Server Error",
  "error": {
    "code": 2,
    "message": "runtime error: invalid memory address or nil pointer dereference",
    "details": []
  }
}

**Comment by james-prysm** [comment]
I believe it's something with how gnosis chain is implemented, the api is around how your validator gets initialized and showing the queue for entry, I'm not sure if gnosis chain works that way but you should check with them.

**Comment by Mettodo** [comment]
Thanks! Will do so and come back here if I do not solve it
