### ISSUE TITLE
500 Internal Server : deleted all validator addresses to add new ones

### ISSUE THREAD

**Issue by blindslug** [prysmaticlabs/prysm-web-ui#228]
```
{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 500,
  "statusText": "Internal Server Error",
  "url": "http://gnosis-beacon-chain-prysm.dappnode/api/v2/validator/accounts?pageSize=5",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for http://gnosis-beacon-chain-prysm.dappnode/api/v2/validator/accounts?pageSize=5: 500 Internal Server Error",
  "error": {
    "code": 13,
    "message": "Could not paginate results: page start 0 >= list 0",
    "details": []
  }
}
```

hello, i wanted to replace the validator addresses, i trashed them one by one, and after the last one was deleted, got this, now i cant add the new ones back

**Comment by blindslug** [comment]
was able to reach the validator upload directly here : [http://gnosis-beacon-chain-prysm.dappnode/dashboard/wallet/accounts/](http://gnosis-beacon-chain-prysm.dappnode/dashboard/wallet/accounts/import)

**Comment by james-prysm** [comment]
@blindslug when you deleted in gnosis did you get your slashing protection data? wondering if I already fixed this in the latest version and it hasn't been updated for gnosis (if you happen to know if gnosis is still on an older version as of writing this)
