### ISSUE TITLE
Issue Importing Wallet Using Avado

### ISSUE THREAD

**Issue by ClubSpeedJustinG** [prysmaticlabs/prysm-web-ui#241]
![image](https://user-images.githubusercontent.com/30958546/213840484-6dd9a486-d0b7-4e7c-a3ca-d9600a173d54.png)

I imported my keys, and I getting an error. Can anybody help with this?

**Comment by ClubSpeedJustinG** [comment]
I am also getting this error:

![image](https://user-images.githubusercontent.com/30958546/213840574-4e7ea29e-a6bb-4a7f-8138-30220d44694d.png)

**Comment by james-prysm** [comment]
Hi sorry for the late response, are you still facing issues?

**Comment by ClubSpeedJustinG** [comment]
On January 22nd at noon the Avado team updated the Prysm Validator package to v0.0.50. After this was done, everything started to work as expected. We can close this issue now. Thanks!
