### ISSUE TITLE
Ensure Password Length Requirements are Enforced

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm-web-ui#62]
We need to ensure that the warning `Password must be at least 8 characters long and contain 1 uppercase letter and 1 special character and 1 number` is accurate. Some users have tried entering those requirements and still cannot pass the proper checks

**Comment by wackerow** [comment]
https://github.com/prysmaticlabs/prysm-web-ui/blob/c37d5d5bbd00d60003d384aac0a0bf8afb344d42/src/app/modules/core/validators/password.validator.ts#L11
Two things I noted in the regex pattern declared in `password.validator.ts`
1. It currently includes `(?=.*[a-z])` which also requires at least one lowercase letter, which is a condition that is not currently being tested for, and fails if you test with all other criteria met except with no lowercase letters. 
2. `(?=.*[0-9])` I believe this will exclude certain digits in other character sets, which `(?=.*\d)` would include, thus if someone relied on a digit from a character set not included this will be blocked. 

Are there any reported exampled of passwords that should match but are failing?

I'd be happy to fix this, but just need to know what the source of truth is... Are we requiring one lowercase letter as well? If so I'll update the test script and the error message being displayed. If we are not requiring one lowercase, I will just update the pattern to not require that.

**Comment by wackerow** [comment]
Also noticing there is no explicit instructions to user about which special characters are valid. 
ie. Entering password `Passw[]rd1` will fail validation, and message is `Needs at least 1 uppercase letter, 1 number, and 1 special char` which could be confusing. 

Adding some text stating that special characters are `@$!%*?&` to provide clarity would help, happy to put this together as well. 
A more forceful option would be to completely prohibit the use of those other characters, and alert the user. 

Again, let me know if you've heard any other specific examples of passwords that failed or passed when they shouldn't have and I will troubleshoot. The above PR fixes the lowercase letter requirement if you choose you want that dropped. If you want to keep a requirement for a lowercase letter, I have another edit in progress that takes that approach.
