### ISSUE TITLE
Creating HD Wallet ends in infinite loop

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm-web-ui#68]
![TeamViewer_2020-10-12_10-47-17](https://user-images.githubusercontent.com/26490734/95726050-b6f43a80-0c78-11eb-96fe-00b57a01b249.png)

![TeamViewer_2020-10-12_10-51-08](https://user-images.githubusercontent.com/26490734/95726179-e0ad6180-0c78-11eb-8978-beb2d74711d9.png)

Also, this little bug 
![TeamViewer_2020-10-12_10-50-26](https://user-images.githubusercontent.com/26490734/95726062-bd82b200-0c78-11eb-803d-35545fc7a9b5.png)

**Comment by Buttaa** [comment]
![TeamViewer_2020-10-12_11-01-47](https://user-images.githubusercontent.com/26490734/95727458-71d10800-0c7a-11eb-8c81-ea01629391e9.png)

**Comment by wackerow** [comment]
Noticed this too and wasn't sure if it was just my end with the dev build... Took a closer look, and when the wizard submits at the end it submits the `authService.signup()` method, turns the `loading` flag back off, but does not call any routing, and indeed just hangs on Step 5 of the stepper with original text and pair of password fields.

Also, `"create"` is the reference to the `mat-icon` being used after these steps have been visited, have you noticed this anywhere else on the page? (ie. Is there an icon of a house to the left of "Dashboard" in the breadcrumb on the `/dashboard` page? or does it say "home"?)

Will take a look further at both of these.

**Comment by wackerow** [comment]
https://github.com/prysmaticlabs/prysm-web-ui/blob/94eee42d4c30b390f4e9863632fe8dc3e30fd928/src/app/modules/onboarding/pages/hd-wallet-wizard/hd-wallet-wizard.component.html#L78 Noticed this div contains `<a routerLink="/dashboard/gains-and-losses">` only if the `depositData` populates after submitting the wizard, which does not appear to be happening on my end. While running the web-ui with `--web`, the api endpoints seem to be working (a GET request to `http://localhost:7500/v2/validator/mnemonic/generate` will return an object with a new mnemonic), though when I do a mock POST request to `http://localhost:7500/v2/validator/wallet/create` to mimic `wallet.service.ts` line 75 ```return this.http.post<CreateWalletResponse>(`${this.apiUrl}/wallet/create`, request);``` I get `"error": "Authorization token could not be found"`. When I do all this through web UI it ends with a red banner at the bottom with `Bad request sent to server, something went wrong`, then the loading div returns to the div with the password fields and the banner disappears.

**Comment by rauljordan** [comment]
HD wallet wizard was removed from beta as it was out of scope and not enough bandwidth for us to support it at this time
