### ISSUE TITLE
password complexity validation logic broken

### ISSUE THREAD

**Issue by wgknowles** [prysmaticlabs/prysm-web-ui#69]
After following the steps to import a wallet, the Ui gets stuck on the last step to select a password.
The UI indicates "Needs at least 1 uppercase letter, 1 number, and 1 special character"
The continue button is greyed out.

**Comment by wgknowles** [comment]
Fyi, was using ! as a special character

**Comment by wgknowles** [comment]
seems to be more related to the order of the required character types

**Comment by wgknowles** [comment]
https://github.com/prysmaticlabs/prysm-web-ui/blob/master/src/app/modules/core/validators/password.validator.ts#L11

I think the issue is the . in here: [A-Za-z\d$@$!%*?&].{8,}',
it's only counting towards 8 characters if they are in the order [caps, lower, digit, symbols]

**Comment by yorickdowne** [comment]
The wallet import does not require this, it's fine with lowercase, number and special, which means a valid password during import will be rejected on UI

**Comment by steakandbake** [comment]
Ack. Web UI requires uppercase letter which was not required during import. Web login password complexity needs to be relaxed.

**Comment by wackerow** [comment]
(Also open in Issue #62)
Currently front-end validation requirements do not match back-end. Will work on a PR to make front-end experience consistent with back-end requirements.
