### ISSUE TITLE
Web UI will not work when running Prysm within a Docker container

### ISSUE THREAD

**Issue by KevinVitale** [prysmaticlabs/prysm-web-ui#72]
The following message appears if attempting to run from a Docker container:

<pre>
<code>
level=error msg="Could not open Prysm web UI in browser" error="exec: "xdg-open": executable file not found in $PATH" prefix=prysm-web
</code>
</pre>

**Comment by yorickdowne** [comment]
installing w3m and xdg-utils inside the docker container seems to work around the issue. Mild panic when shutting down the validator, however:

```
[2020-10-12 13:45:56]  INFO prysm-web: Starting Prysm web UI address=127.0.0.1:4242
^C[2020-10-12 13:46:03]  INFO node: Got interrupt, shutting down...
[2020-10-12 13:46:03] ERROR prysm-web: Failed to start validator web server error=http: Server closed
[2020-10-12 13:46:03]  INFO validator: Stopping service
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x20125d2]

goroutine 139 [running]:
github.com/prysmaticlabs/prysm/shared/slotutil.(*SlotTicker).Done.func1(0x0)
        shared/slotutil/slotticker.go:37 +0x22
created by github.com/prysmaticlabs/prysm/shared/slotutil.(*SlotTicker).Done
        shared/slotutil/slotticker.go:36 +0x3f
```

**Comment by yorickdowne** [comment]
I have the --web interface prompting me for password after installing w3m and xdg-utils in the validator docker, however the web interface then complains "no response, perhaps the beacon node or validator client are not running".

**Comment by squeakyguacamole** [comment]
Just want to add that this also happens when running Prysm on VPS (without Docker)

**Comment by ibwitlin** [comment]
This happens to me running prysm using https://raw.githubusercontent.com/prysmaticlabs/prysm/master/prysm.sh

**Comment by Greyhair0** [comment]
I have a VPS and have same issue, i can't run with the --web parameter.

**Comment by rauljordan** [comment]
Fixed by https://github.com/prysmaticlabs/prysm/pull/7569, will be updated in the beta.0 release this week
