### ISSUE TITLE
Current Slot Counter in BeaconNodeConnectionComponent is Negative Before Genesis

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm-web-ui#74]
<img width="397" alt="Screen Shot 2020-10-12 at 4 31 59 PM" src="https://user-images.githubusercontent.com/5572669/95792137-77dddd80-0ca8-11eb-95ca-99af5f6ff0d7.png">

**Comment by wackerow** [comment]
How about a custom pipe that renders any negative slot numbers being returned to 'awaiting genesis'?
