### ISSUE TITLE
Write E2E Tests With Protractor

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm-web-ui#77]
Thanks @rkapka for bringing this up. We should be writing end to end tests for the application, especially for features such as the onboarding process. Angular makes this easy with the built-in e2e folder using the protractor testing library.

An example of an end-to-end test would take us through the wallet selection screen, go through the HD wallet onboarding, confirm the mnemonic phrase, pick the number of accounts, select a wallet password, then proceed to create the wallet. We should be checking behavior is as expected all along the way

**Comment by wackerow** [comment]
Will begin working on e2e tests focusing on onboarding process to start.

**Comment by james-prysm** [comment]
no longer needed
