### ISSUE TITLE
Allow Seed Phrases in Language Other Than English

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm-web-ui#78]
Right now, our onboarding portal for HD wallets only allows english mnemonics, but we should allow the user to select the desired language from the available bip mnemonic language list. This would be a select dropdown in the frontend and also require modifications on the backend

**Comment by chrishobcroft** [comment]
Here's some inspiration from Google Translate:

![image](https://user-images.githubusercontent.com/2212651/95883315-683dc200-0d98-11eb-96b1-10150d0e1740.png)

**Comment by wackerow** [comment]
I'm happy to help with the front end, but as you noted, this appears to be linked directly to the backend, endpoint `localhost:7500/v2/validator/mnemonic/generate`. Right now this only produces english mnemonics from the BIP39 English dictionary built into [site_data.go](https://github.com/prysmaticlabs/prysm/blob/master/validator/web/site_data.go).

Can't help with the Go side, but if someone is able to bring the [word lists](https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md) from other languages in, then happy to help with front end

**Comment by chrishobcroft** [comment]
I am happy to help source word libraries for as many languages as I can... is someone able to confirm what is specifically required to be provided, and whether it's possible for them to be "plugged in".

Alternatively I wonder if this issue might be better addresses here: https://github.com/ethereum/eth2.0-deposit-cli/

**Comment by wackerow** [comment]
Hey @chrishobcroft - responded to https://github.com/ethereum/eth2.0-deposit-cli/issues/135 and thought I'd comment here too... https://github.com/bitcoin/bips/tree/master/bip-0039 contains all the information about BIP39, the languages supported, the words chosen and why. Expanding language support for mnemonic phrases would likely be accomplished through that repo, and not at this level. 

That being said, 9 languages are supported by BIP39, yet Prysm currently only allows English, and I believe this was what @rauljordan was referring to fixing. The word lists are out there, but they are not currently imported into the Prysm (Go) repo (last I checked)... This appears to be a requirement before the Web-UI front-end will be able to incorporate this (currently the API call only produces English mnemonics, and this cannot be fixed from within this repo (on that note, maybe we should relocate this issue to that repo?)

**Comment by rauljordan** [comment]
Done by @olehyev138
