### ISSUE TITLE
UX Suggestion: Preformatted text styling

### ISSUE THREAD

**Issue by wackerow** [prysmaticlabs/prysm-web-ui#86]
### Description
Currently Step 3 of the HD onboarding wizard lists the default wallet paths for three OSs. These path names (ie. {{linux}}), when rendered, are difficult to read, especially when three are placed in serial with no intentional line breaks.
![image](https://user-images.githubusercontent.com/54227730/96785865-49e15300-13a4-11eb-8d21-f61d63806c8d.png)

### Suggested fix
- Put these three into a stacked `<ul>`
- Consider adding a reusable css class for preformatted text, something like:
```
span.preformatted {
  font-family: monospace;
  white-space: pre;
  border: 1px solid $paper;
  background-color: rgba(0, 0, 0, 0.5);
  display: inline;
  padding-left: 7px;
  padding-right: 7px;
  border-radius: 5px;
}
```
...in `/src/styles.scss` and wrap these in `<span class="preformatted"></span>`... gives it a markdown/terminal feel many of us are used to.
- Example render:
![image](https://user-images.githubusercontent.com/54227730/96786102-a04e9180-13a4-11eb-8a19-de0120f4eadf.png)

**Comment by wackerow** [comment]
@rauljordan Btw, I have a [branch on my fork](https://github.com/wackerow/prysm-web-ui/tree/w/preformatted) with this change already implemented. If you're interested just assign me and I'll put it into a PR. Suggestions/thoughts welcome too!

**Comment by rauljordan** [comment]
We no longer allow custom wallet directories from the UI for security reasons, so we can close this issue
