### ISSUE TITLE
UI/UX bug: Contents of HD Wizard not fitting within container causing clipping

### ISSUE THREAD

**Issue by wackerow** [prysmaticlabs/prysm-web-ui#87]
### Description
HD wallet wizard was recently updated to include an additional step for the creation of a 'web password'. On standard desktop screens, the `mat-horizontal-stepper` is used, and with this additional step the wizard is now wider. This is not an issue on smaller screen/window sizes where the `mat-vertical-stepper` is used, as this expanded vertically. 

On standard desktop screens this now causes clipping on the right edge of the wizard, and requires you to scroll horizontally within the wizard to see the clipped contents. 

#### Screenshots
<img width="1216" alt="Screen Shot 2020-10-21 at 11 02 56" src="https://user-images.githubusercontent.com/54227730/96786445-25d24180-13a5-11eb-8c89-0ce846bdbabe.png">
<img width="1210" alt="Screen Shot 2020-10-21 at 11 03 29" src="https://user-images.githubusercontent.com/54227730/96786448-27036e80-13a5-11eb-85f0-091135bd1f4f.png">
<img width="1473" alt="Screen Shot 2020-10-21 at 11 05 23" src="https://user-images.githubusercontent.com/54227730/96786449-28349b80-13a5-11eb-8629-023a04b0fbe9.png">

**Comment by rauljordan** [comment]
HD wallet wizard was removed from beta as it was out of scope and not enough bandwidth for us to support it at this time
