### ISSUE TITLE
Websocket endpoints are hardcoded to localhost

### ISSUE THREAD

**Issue by dapplion** [prysmaticlabs/prysm-web-ui#92]
Deploying the beacon-chain and validator binaries in separate docker containers there needs to be a way to specify where those are in order to fetch the logs. At least the validator ws endpoint could use the origin of the UI instead of localhost

https://github.com/prysmaticlabs/prysm-web-ui/blob/384e366a2e3b562302cf28c56117c55dfbf9a127/src/app/modules/core/constants.ts#L11-L12

**Comment by fireheadman** [comment]
+1.... having issue where logs are not showing up in webUI
Running beacon/validator on same node, using ssh tunnel to connect to webUI

![image](https://user-images.githubusercontent.com/19847195/100282631-3425f700-2f29-11eb-9cfa-e118f98b82b2.png)

**Comment by MaximFMai** [comment]
+1 same issue. Running prysm mainnet package on dappnode, connected through WiFi. Logs on Dappnode UI look fine.
