### ISSUE TITLE
Web UI dashboard is not showing all the keys pending exit

### ISSUE THREAD

**Issue by akarub** [prysmaticlabs/prysm-web-ui#95]
The Web UI dashboard is not showing all the keys pending exit.

![prysm_webui](https://user-images.githubusercontent.com/74686152/99595125-12d67f80-29ec-11eb-92fb-5cafcc4ec016.png)

**Comment by mohamedmansour** [comment]
This would be a simple fix, I will take it on after work tonight

**Comment by james-prysm** [comment]
widget has been removed for a few releases
