### ISSUE TITLE
Beaconcha.in link doesn't point to testnet

### ISSUE THREAD

**Issue by dapplion** [prysmaticlabs/prysm-web-ui#97]
Link in actions points to mainnet when running on the Pyrmont network

<img width="1901" alt="Screenshot_2020-11-23_at_19 25 41" src="https://user-images.githubusercontent.com/35266934/100000517-9829ad80-2db9-11eb-8c6a-6b3b1c9df9bf.png">

**Comment by rauljordan** [comment]
This is a niche feature we will likely not be able to support due to limited bandwidth, as it would require a few changes in the backend to do so
